### ISSUE TITLE
I do not see Oncology Neuroexam Unit  and Technologist demand in game!

### ISSUE THREAD

**Issue by U-ru-Ru** [sleepy068/ProjectHospital_Oncology#1]
U have this strings in ModStringTableEnBuildingMode 
`<GameDBLocalizedString>
		<LocID>ROOM_TYPE_ONCO_NEURODIAGNOSTIC_UNIT_NE</LocID>                   
		<Text>Oncology Neuroexam Unit</Text>  
	</GameDBLocalizedString>`
but i dont see it in game
![issue gh](https://user-images.githubusercontent.com/60316953/73588600-a5f60580-44fd-11ea-88e0-521794878a2e.jpg)

**Comment by sleepy068** [comment]
Hi U-ru-Ru, they aren't suppose to be in the mod yet, I was originally testing the idea of adding Neurology skills to Oncology doctors so I could integrate the two (like a sub-department of Oncology) but it just didn't work out as well as I hoped and the learning curve was a bit too steep for the player. I ended up adding Brain cancer to Neurology instead. 

I can remove it but leaving the localisation in doesn't have a negative effect on the game and the player will never know, so I tend to leave them in just in case I want to revisit it later. Hope that clears it up.

**Comment by U-ru-Ru** [comment]
ok.
